CREATE TABLE RECIPE (
    ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(50),
    DIRECTIONS VARCHAR(8000)
 );

CREATE TABLE INGREDIENT (
    ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(50)
 );